### ISSUE TITLE
[Analyst] Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by faustbrian** [faustbrian/core-payroll#17]
Currently when previous blocks are indexed via https://github.com/faustbrian/core-payroll/blob/master/lib/indexers/blocks.js on launch of the relay the payroll for whatever reason is empty while it works just fine if the payroll is created outside of the initial launch.

```
10|ark-core-relay  | (node:18485) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
10|ark-core-relay  |     at Analyst.__updatePayroll (/home/ark/ark-core/plugins/core-payroll/lib/payroll/analyst.js:111:59)
10|ark-core-relay  |     at Analyst.hasSufficientFunds (/home/ark/ark-core/plugins/core-payroll/lib/payroll/analyst.js:84:20)
10|ark-core-relay  |     at <anonymous>
10|ark-core-relay  | (node:18485) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 530)
```

Could either be an issue with my config because I do a payout every block, which could result in a race condition, or the payroll creation fails altogether.

**Comment by faustbrian** [comment]
Looks like a race condition with my config of doing payouts for every single forged block which seems to be only an issue during indexing of past blocks on launch because dozens of payout runs are launched at the same time.

**Comment by faustbrian** [comment]
https://github.com/faustbrian/core-payroll/commit/a366ba677fd6c629075008f5c956c76ec6c65fee
